server:
  port: 8081

spring:
  application:
    name: customer-bcs
  r2dbc:
    url: r2dbc:h2:mem:///ibkchallenge?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    initialization-mode: always

h2-server:
    port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"