server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          oauth-client:
            provider: oauth-server
            client-id: oauth-client
            client-secret: 12345678910
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: openid,profile,read,write
            client-name: oauth-client
        provider:
          oauth-server:
            issuer-uri: http://127.0.0.1:9000
  application:
    name: customer-products-bff

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"